swagger: "2.0"
info:
  version: "0.0.1"
  title: Startegy
# during dev, should point to your local machine
host: localhost:10030
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: api-key
paths:
  /strategies:
    x-swagger-router-controller: strategy.controller
    get:
      tags: 
        - strategy
      security:
        - api_key: []
      description: Returns a list of available strategies
      produces:
        - application/json
      operationId: get
      parameters: 
        - name: _id
          in: query
          description: The id of a specific strategy
          required: false
          type: string
      responses:
        "200":
          description: A list of strategies
          schema: 
            type: array
            items:
              $ref: "#/definitions/Strategy"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags: 
        - strategy
      security:
        - api_key: []
      description: adds a new strategy
      produces:
        - application/json
      operationId: post
      parameters:
        - name: strategy
          description: the complete strategy object
          in: body
          required: true
          schema:
            $ref: "#/definitions/Strategy"
      responses:
        200:
          description: OK - created successfully
          schema: 
            $ref: "#/definitions/Strategy"
  /strategy/events:
    x-swagger-router-controller: strategy-event.controller
    get:
      tags: 
        - strategy-event
      security:
        - api_key: []
      description: Returns the events where the strategy hooked up to
      produces:
        - application/json
      operationId: getEvents
      parameters: 
        - name: id
          in: query
          description: The id of a specific strategy
          required: true
          type: string
      responses:
        "200":
          description: A list of events
          schema: 
            type: array
            items:
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags: 
        - strategy-event
      security:
        - api_key: []
      description: adds a new event to the list of events of a strategy
      operationId: postEvent
      parameters:
        - name: id
          in: query
          description: The id of a specific strategy
          required: true
          type: string
        - name: events
          description: the event that strategy hooks up to
          in: body
          required: true
          schema: 
            type: array
            items:
              type: string
      responses:
        200:
          description: OK - created successfully
          schema: 
            $ref: "#/definitions/Strategy"
  /strategies/backtest:
    x-swagger-router-controller: strategy.controller
    patch:
      tags: 
        - strategy
      security:
        - api_key: []
      description: starts backtesting a strategy
      operationId: backtest
      parameters:
        - name: instrument
          description: the instrument in which the stratgey is backtested
          in: query
          required: true
          type: string
          enum:
            - AUD_USD
        - name: strategy
          description: the strategy to be backtested
          type: string
          in: query
          required: true
        - name: payload
          description: the payload which contains a description for the backtest
          in: body
          schema:
            type: object
            properties:
              description:
                type: string
                description: a description for the backtest
                example: testing with RSA added to the strategy
              
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Strategy:
    type: object
    required:
      - name
      - description
      - postedBy
    properties:
      name:
        type: string
      description:
        type: string
      postedBy:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  EventResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    properties:
      message:
        type: string
    required:
      - message